version: '3.6'
services:
  webapp:
    build:
      context: ./
      dockerfile: ./webapp/Dockerfile
    image: webapp_image:1
    container_name: webapp_container
    depends_on:
      - mysql_service
    command: sh
    ports:
      - "9876:9876"
    volumes:
      - ./src:/home/app_user/pg_manager/src
    environment:
      # - MODULE=webapp
      # - STATUS=test
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: mynet